### YamlMime:Lifecycle
metadata:
  title: Microsoft Intelligent Application Gateway 2007
  description: Microsoft Intelligent Application Gateway 2007 ievēro fiksētā dzīves cikla politiku.
  ms.date: 07/28/2020
  ms.openlocfilehash: 2e4cb68a2f1b63fbdc64507b9b16fbdc2f8008a0
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: lv-LV
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4114637"
name: Microsoft Intelligent Application Gateway 2007
summary: >
  Microsoft Intelligent Application Gateway 2007 ievēro [fiksētā](/lifecycle/policies/fixed) dzīves cikla politiku.



  > [!IMPORTANT]

  > Šī produkta atbalsts ir beidzies. Skatiet tālāk sniegtās migrācijas vadlīnijas.
products:
- microsoft-servers
policyType: fixed
supportDates:
  start: 2007-06-01T00:00:00.000-08:00
  end: 2012-07-10T22:59:59.999-08:00
  extendedEnd: 2017-07-11T22:59:59.999-08:00
releases:
- version: Service Pack 2
  startDate: 2008-11-27T00:00:00.000-08:00
  endDate: 2017-07-11T22:59:59.999-08:00
- version: Service Pack 1
  startDate: 2007-09-03T00:00:00.000-08:00
  endDate: 2010-01-12T22:59:59.999-08:00
- version: Original Release
  startDate: 2007-06-01T00:00:00.000-08:00
  endDate: 2008-10-14T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Saites \n* [Microsoft Intelligent Application Gateway 2007 ceļvedis](/archive/blogs/testtesttestbug/important-changes-to-the-forefront-product-line)\n* [Servisa pakotnes politika](/lifecycle/policies/fixed#service-packs)"
