### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 5.1 Windows datoriem
  description: Microsoft Application Virtualization Hosting 5.1 Windows datoriem ievēro fiksētā dzīves cikla politiku.
  ms.date: 09/10/2020
  keywords: for Windows Desktops
name: Microsoft Application Virtualization Hosting 5.1 Windows datoriem
summary: |+
  Microsoft Application Virtualization Hosting 5.1 Windows datoriem ievēro [fiksētā](/lifecycle/policies/fixed) dzīves cikla politiku.

  Tas attiecas uz šādiem izdevumiem: Windows darbvirsmām

products:
  - windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
  - version: Original Release
    startDate: 11/01/2015
    endDate: 04/14/2026
content: |

  ## <a name="links"></a>Saites 
  * [Informācija par produktu](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)


  ## <a name="editions"></a>Izdevumi 
  * Windows darbvirsmām