### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager (LTSB - versija 1606)
  description: Microsoft System Center Configuration Manager (LTSB - versija 1606) ievēro fiksētā dzīves cikla politiku.
  ms.date: 08/20/2020
  ms.openlocfilehash: 6475679aee15c8748a0fc3092509dee7010472d848ac73e54be2c605a19595e5
  ms.sourcegitcommit: 1c28c95e7a2b743cff45216da63f72ffbad026ed
  ms.translationtype: HT
  ms.contentlocale: lv-LV
  ms.lasthandoff: 08/06/2021
  ms.locfileid: "2511248"
name: Microsoft System Center Configuration Manager (LTSB - versija 1606)
summary: >+
  Microsoft System Center Configuration Manager (LTSB - versija 1606) ievēro [fiksētā](/lifecycle/policies/fixed) dzīves cikla politiku.


products:
- m365
policyType: fixed
supportDates:
  start: 10/12/2016
  end: 10/12/2021
  extendedEnd: 01/12/2027
releases:
- version: Original Release
  startDate: 10/12/2016
  endDate: 01/12/2027
content: "\n## <a name=\"links\"></a>Saites \n* [Apkalpošanas un atbalsta informācija](/sccm/core/understand/learn-more-editions)"
