### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 5.1 Windows datoriem
  description: Microsoft Application Virtualization Hosting 5.1 Windows datoriem ievēro fiksētā dzīves cikla politiku.
  ms.date: 09/10/2020
  keywords: for Windows Desktops
  ms.openlocfilehash: eb73a1103424c9b0900a18fc09bb6bc0685b646d
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: lv-LV
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4114304"
name: Microsoft Application Virtualization Hosting 5.1 Windows datoriem
summary: >+
  Microsoft Application Virtualization Hosting 5.1 Windows datoriem ievēro [fiksētā](/lifecycle/policies/fixed) dzīves cikla politiku.


  Tas attiecas uz šādiem izdevumiem: Windows darbvirsmām

products:
- windows
policyType: fixed
supportDates:
  start: 2015-11-01T00:00:00.000-08:00
  end: 2018-01-09T22:59:59.999-08:00
  extendedEnd: 2026-04-14T22:59:59.999-08:00
releases:
- version: Original Release
  startDate: 2015-11-01T00:00:00.000-08:00
  endDate: 2026-04-14T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Saites \n* [Informācija par produktu](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n\n\n## <a name=\"editions\"></a>Izdevumi \n* Windows darbvirsmām"
