### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront Client Security ievēro fiksētā dzīves cikla politiku.
  ms.date: 08/28/2020
name: Microsoft Forefront Client Security
summary: |+
  Microsoft Forefront Client Security ievēro [fiksētā](/lifecycle/policies/fixed) dzīves cikla politiku.


products:
  - msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
  - version: Original Release
    startDate: 08/02/2007
    endDate: 07/14/2015
content: |+

  ## <a name="links"></a>Saites 
  * [System Center Endpoint Protection](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)

  > [!NOTE]
  > Forefront Client Security darbība ir pārtraukta no 2015. gada 14. jūlija. Ļaunprogrammatūras novēršanas un pretspiegprogrammatūras definīciju atjauninājumi vairs nebūs pieejami pēc produkta versijas atbalsta beigām. Lūdzu, novērtējiet System Center Endpoint Protection kā aizstājēju.