### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront Client Security ievēro fiksēto dzīves cikla politiku.
  ms.date: 08/21/2020
  ms.openlocfilehash: 802c6836324ac39b0b8ffc99c1f7f6734906445b
  ms.sourcegitcommit: 2f3e18a9447115504ef274bd044dbcdb08231f5b
  ms.translationtype: MT
  ms.contentlocale: lv-LV
  ms.lasthandoff: 08/25/2020
  ms.locfileid: "908820"
name: Microsoft Forefront Client Security
summary: >+
  Microsoft Forefront Client Security ievēro [fiksēto](/lifecycle/policies/fixed) dzīves cikla politiku.


products:
- msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
- version: Original Release
  startDate: 08/02/2007
  endDate: 07/14/2015
content: "\n## <a name=\"links\"></a>Saites \n* [System Center Endpoint Protection](http://www.microsoft.com/server-cloud/products/system-center-2012-r2-configuration-manager/default.aspx)\n\n> [!NOTE]\n> Forefront Client Security ir izbeigta. Atbalsts beidzas ar 14. jūliju, 2015. Ļaunprogrammatūras un pretspiegprogrammatūras definīciju atjauninājumi vairs nebūs pieejami pēc produkta versijas atbalsta beigām. Lūdzu, novērtējiet System Center Endpoint Protection kā aizstājēju."
