### YamlMime:Lifecycle
metadata:
  title: Vaļu sakaru inteliģentās lietojumprogrammas vārteja
  description: Vaļu sakaru inteliģentās lietojumprogrammas vārteja ievēro fiksēto dzīves cikla politiku.
  ms.date: 08/21/2020
  ms.openlocfilehash: 4946cfbd0c53706853138bd707157a5c318b8dc6
  ms.sourcegitcommit: bc7fcda30191f92db77ed2e7f74d5816ac276a55
  ms.translationtype: MT
  ms.contentlocale: lv-LV
  ms.lasthandoff: 08/21/2020
  ms.locfileid: "907148"
name: Vaļu sakaru inteliģentās lietojumprogrammas vārteja
summary: >+
  Vaļu sakaru inteliģentās lietojumprogrammas vārteja ievēro [fiksēto](/lifecycle/policies/fixed) dzīves cikla politiku.


products:
- windows
policyType: fixed-mainstream-only
supportDates:
  start: 10/10/2007
  end: 07/13/2010
releases:
- version: "3.1"
  startDate: 10/10/2007
  endDate: 07/08/2008
- version: "3.6"
  startDate: 10/10/2007
  endDate: 07/13/2010
content: "\n\n> [!NOTE]\n> Šī produkta atbalstu nosaka tā iegādes nosacījumi."
